Ingredient.create(name: "Lemon")
Ingredient.create(name: "Ice")
Ingredient.create(name: "Mint leaves")
Ingredient.create(name: "Light rum")
Ingredient.create(name: "Applejack")
Ingredient.create(name: "Gin")
Ingredient.create(name: "Dark rum")
Ingredient.create(name: "Sweet vermouth")
Ingredient.create(name: "Strawberry schnapps")
Ingredient.create(name: "Scotch")
Ingredient.create(name: "Champagne")
Ingredient.create(name: "Vodka")
Ingredient.create(name: "Cranberry juice")
Ingredient.create(name: "Pineapple juice")
Ingredient.create(name: "Tequila")
Ingredient.create(name: "Sugar")
Ingredient.create(name: "Grenadine")
Ingredient.create(name: "Ginger")
Ingredient.create(name: "Pisco")
Ingredient.create(name: "Lemonade")
Ingredient.create(name: "Cachaca")

